# syntax=docker/dockerfile:1

FROM node:20-alpine AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_ADMIN_API_BASE_URL=http://localhost:8080
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
ARG NEXT_PUBLIC_CLERK_SIGN_IN_URL=/login
ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard
ARG NEXT_PUBLIC_CLERK_JWT_TEMPLATE=aniyume_admin
ARG NEXT_PUBLIC_UPTIME_KUMA_URL=
ARG NEXT_PUBLIC_GRAFANA_URL=
ARG NEXT_PUBLIC_NOCODB_URL=
ARG NEXT_PUBLIC_UNDERSTAND_ANYTHING_URL=
ARG NEXT_PUBLIC_UPTIME_KUMA_EMBED=false
ARG NEXT_PUBLIC_GRAFANA_EMBED=false
ARG NEXT_PUBLIC_NOCODB_EMBED=false
ARG NEXT_PUBLIC_UNDERSTAND_ANYTHING_EMBED=false
ENV NEXT_PUBLIC_ADMIN_API_BASE_URL=$NEXT_PUBLIC_ADMIN_API_BASE_URL
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ENV NEXT_PUBLIC_CLERK_JWT_TEMPLATE=$NEXT_PUBLIC_CLERK_JWT_TEMPLATE
ENV NEXT_PUBLIC_UPTIME_KUMA_URL=$NEXT_PUBLIC_UPTIME_KUMA_URL
ENV NEXT_PUBLIC_GRAFANA_URL=$NEXT_PUBLIC_GRAFANA_URL
ENV NEXT_PUBLIC_NOCODB_URL=$NEXT_PUBLIC_NOCODB_URL
ENV NEXT_PUBLIC_UNDERSTAND_ANYTHING_URL=$NEXT_PUBLIC_UNDERSTAND_ANYTHING_URL
ENV NEXT_PUBLIC_UPTIME_KUMA_EMBED=$NEXT_PUBLIC_UPTIME_KUMA_EMBED
ENV NEXT_PUBLIC_GRAFANA_EMBED=$NEXT_PUBLIC_GRAFANA_EMBED
ENV NEXT_PUBLIC_NOCODB_EMBED=$NEXT_PUBLIC_NOCODB_EMBED
ENV NEXT_PUBLIC_UNDERSTAND_ANYTHING_EMBED=$NEXT_PUBLIC_UNDERSTAND_ANYTHING_EMBED
RUN mkdir -p public && npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3001
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3001

CMD ["node", "server.js"]
