"use client";

import { FormEvent, useEffect, useState } from "react";
import { Badge, Card, EmptyState, ErrorState, LoadingState, PageHeader, formatDate, formatNumber } from "@/components/ui";
import { AdminEpisode, PaginationMeta, deleteAdminEpisode, getAdminEpisodes, importAllEpisodes, importEpisodesForAnime, updateAdminEpisode } from "@/lib/admin-api";
import { useUi } from "@/features/ui/ui-provider";

type Filters = { search: string; anime_id: string; source: string };
type EpisodeForm = { episode_number: string; season_number: string; title: string; player_url: string; player_iframe: string; release_date: string; duration: string; translator: string; quality: string; source: string };
const initialFilters: Filters = { search: "", anime_id: "", source: "" };

function formFromEpisode(episode: AdminEpisode): EpisodeForm {
  return { episode_number: String(episode.episode_number ?? ""), season_number: String(episode.season_number ?? ""), title: episode.title ?? "", player_url: episode.player_url ?? "", player_iframe: episode.player_iframe ?? "", release_date: episode.release_date?.slice(0, 10) ?? "", duration: episode.duration ? String(episode.duration) : "", translator: episode.translator ?? "", quality: episode.quality ?? "", source: episode.source ?? "" };
}

export default function EpisodesPage() {
  const [items, setItems] = useState<AdminEpisode[]>([]);
  const [meta, setMeta] = useState<PaginationMeta | undefined>();
  const [filters, setFilters] = useState(initialFilters);
  const [applied, setApplied] = useState(initialFilters);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [editing, setEditing] = useState<AdminEpisode | null>(null);
  const [form, setForm] = useState<EpisodeForm | null>(null);
  const [importSource, setImportSource] = useState("all");
  const [importLimit, setImportLimit] = useState("500");
  const ui = useUi();

  function load() { setLoading(true); getAdminEpisodes({ ...applied, page, per_page: 50 }).then((result) => { if (result.ok) { setItems(result.data.data); setMeta(result.data.meta); setError(null); } else setError(result.message); }).finally(() => setLoading(false)); }
  useEffect(load, [applied, page]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPage(1); setApplied(filters); }
  function openEditor(episode: AdminEpisode) { setEditing(episode); setForm(formFromEpisode(episode)); }
  async function saveEpisode(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing || !form) return;
    const result = await updateAdminEpisode(editing.id, { episode_number: Number(form.episode_number), season_number: form.season_number === "" ? null : Number(form.season_number), title: form.title || null, player_url: form.player_url || null, player_iframe: form.player_iframe || null, release_date: form.release_date || null, duration: form.duration === "" ? null : Number(form.duration), translator: form.translator || null, quality: form.quality || null, source: form.source || null });
    if (result.ok) { setNotice("Episode updated"); ui.toast({ tone: "success", title: "Episode updated" }); setEditing(null); setForm(null); load(); } else { setError(result.message); ui.toast({ tone: "error", title: "Ошибка", message: result.message }); }
  }
  async function remove(episode: AdminEpisode) { if (!await ui.confirm({ title: "Удалить серию", message: `Episode #${episode.episode_number} (${episode.anime?.title ?? episode.anime_id}) будет удалён.`, confirmLabel: "Delete", danger: true })) return; const result = await deleteAdminEpisode(episode.id); if (result.ok) { setNotice("Episode deleted"); ui.toast({ tone: "success", title: "Episode deleted" }); load(); } else { setError(result.message); ui.toast({ tone: "error", title: "Ошибка", message: result.message }); } }
  async function importFor(episode: AdminEpisode) { const result = await importEpisodesForAnime(episode.anime_id, { source: importSource, only_missing: false, update: true }); if (result.ok) { setNotice(`Episodes import queued · ${result.data.data.source ?? importSource}`); ui.toast({ tone: "success", title: "Episodes import queued" }); } else { setError(result.message); ui.toast({ tone: "error", title: "Ошибка", message: result.message }); } }
  async function importAll() { const limit = Math.max(1, Math.min(Number(importLimit) || 500, 5000)); if (!await ui.confirm({ title: "Mass import episodes", message: `Запустить импорт для anime без серий? Source: ${importSource}, limit: ${limit}`, confirmLabel: "Запустить" })) return; const result = await importAllEpisodes({ source: importSource, only_missing: true, limit }); if (result.ok) { const title = `Bulk import queued: ${result.data.data.queued_count} · ${result.data.data.source ?? importSource}`; setNotice(title); ui.toast({ tone: "success", title }); } else { setError(result.message); ui.toast({ tone: "error", title: "Ошибка", message: result.message }); } }

  return <section className="page"><PageHeader kicker="streaming management" title="Episodes" description="Управление сериями, источниками, переводчиками и массовым импортом." actions={<button className="button" onClick={importAll} type="button">⇣ Import missing</button>} />
    <Card><div className="toolbar" style={{ alignItems: "end" }}><label><span className="stat-card-label">Import source</span><select className="input" value={importSource} onChange={(e) => setImportSource(e.target.value)}><option value="all">All providers</option><option value="anilibria">AniLibria</option><option value="kodik">Kodik</option><option value="videocdn">VideoCDN</option><option value="external">External players</option></select></label><label><span className="stat-card-label">Limit</span><input className="input" value={importLimit} onChange={(e) => setImportLimit(e.target.value)} /></label><button className="button" onClick={importAll} type="button">Импорт anime без серий</button><p className="muted" style={{ margin: 0 }}>External players работают только если в API .env заданы URL templates.</p></div></Card>
    <Card><form className="filter-row" onSubmit={submit}><input className="input" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Anime / title / translator" /><input className="input" value={filters.anime_id} onChange={(e) => setFilters({ ...filters, anime_id: e.target.value })} placeholder="Anime ID" /><input className="input" value={filters.source} onChange={(e) => setFilters({ ...filters, source: e.target.value })} placeholder="Source" /><button className="button secondary" type="submit">Фильтровать</button></form></Card>
    {notice ? <div className="pill" style={{ borderColor: "rgba(52,211,153,.35)", color: "var(--success)" }}>{notice}</div> : null}
    {loading ? <LoadingState label="Загружаем episodes…" /> : null}{error ? <ErrorState message={error} /> : null}{!loading && !error && items.length === 0 ? <EmptyState title="Серии не найдены" /> : null}
    {!loading && !error && items.length > 0 ? <Card><div className="toolbar" style={{ marginBottom: 16 }}><h2 style={{ margin: 0 }}>Episodes table</h2><span className="pill">{formatNumber(meta?.total)} episodes</span></div><div className="table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Anime</th><th>Episode</th><th>Title</th><th>Source</th><th>Translator</th><th>Quality</th><th>Release</th><th>Player</th><th>Actions</th></tr></thead><tbody>{items.map((episode) => <tr key={episode.id}><td>#{episode.id}</td><td><strong>{episode.anime?.title ?? `Anime #${episode.anime_id}`}</strong><br /><span className="muted">/{episode.anime?.slug ?? episode.anime_id}</span></td><td><Badge tone="brand">S{episode.season_number ?? 1} · EP {episode.episode_number}</Badge></td><td>{episode.title ?? "—"}</td><td>{episode.source ?? "—"}</td><td>{episode.translator ?? "—"}</td><td>{episode.quality ?? "—"}</td><td>{formatDate(episode.release_date ?? episode.aired_at)}</td><td>{episode.player_url || episode.player_iframe ? <Badge tone="success">ready</Badge> : <Badge tone="warning">missing</Badge>}</td><td><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button className="button secondary" onClick={() => openEditor(episode)} type="button">Edit</button><button className="button secondary" onClick={() => importFor(episode)} type="button">Import</button><button className="button secondary" onClick={() => remove(episode)} type="button">Delete</button></div></td></tr>)}</tbody></table></div><div className="toolbar" style={{ marginTop: 16 }}><button className="button secondary" disabled={page <= 1} onClick={() => setPage((p) => Math.max(1, p - 1))}>← Назад</button><span className="muted">Страница {meta?.current_page ?? page} из {meta?.last_page ?? 1}</span><button className="button secondary" disabled={meta ? page >= meta.last_page : true} onClick={() => setPage((p) => p + 1)}>Вперёд →</button></div></Card> : null}
    {editing && form ? <div className="drawer-backdrop" onMouseDown={(e) => { if (e.currentTarget === e.target) setEditing(null); }}><aside className="drawer-panel"><div className="drawer-header"><div><p className="kicker">episode editor</p><h2 style={{ margin: 0 }}>{editing.anime?.title ?? `Anime #${editing.anime_id}`}</h2><p className="muted">Episode ID #{editing.id}</p></div><button className="button secondary" onClick={() => setEditing(null)} type="button">×</button></div><form className="form-grid" onSubmit={saveEpisode}><div className="form-grid two"><label><span className="stat-card-label">Episode</span><input className="input" value={form.episode_number} onChange={(e) => setForm({ ...form, episode_number: e.target.value })} /></label><label><span className="stat-card-label">Season</span><input className="input" value={form.season_number} onChange={(e) => setForm({ ...form, season_number: e.target.value })} /></label></div><label><span className="stat-card-label">Title</span><input className="input" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label><span className="stat-card-label">Player URL</span><input className="input" value={form.player_url} onChange={(e) => setForm({ ...form, player_url: e.target.value })} /></label><label><span className="stat-card-label">Player iframe</span><textarea className="input" rows={5} value={form.player_iframe} onChange={(e) => setForm({ ...form, player_iframe: e.target.value })} /></label><div className="form-grid two"><label><span className="stat-card-label">Release date</span><input className="input" type="date" value={form.release_date} onChange={(e) => setForm({ ...form, release_date: e.target.value })} /></label><label><span className="stat-card-label">Duration seconds</span><input className="input" value={form.duration} onChange={(e) => setForm({ ...form, duration: e.target.value })} /></label><label><span className="stat-card-label">Translator</span><input className="input" value={form.translator} onChange={(e) => setForm({ ...form, translator: e.target.value })} /></label><label><span className="stat-card-label">Quality</span><input className="input" value={form.quality} onChange={(e) => setForm({ ...form, quality: e.target.value })} /></label></div><label><span className="stat-card-label">Source</span><input className="input" value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })} /></label><button className="button" type="submit">Сохранить episode</button></form></aside></div> : null}
  </section>;
}
